repository:
  name: test-set
  private: false
  
  labels:
    include:
      - name: documentation
        color: '#0075ca'
        description: Improvements or additions to documentation
      - name: done
        color: '#01ca11'
        description: done
      - name: env=dev
        color: '#DEBC7B'
        description: env=dev
